/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void RecipeSaving(GPanel source, GEvent event) { //_CODE_:RecipeSaver:291574:
  } //_CODE_:RecipeSaver:291574:

public void RecipeSaved(GButton source, GEvent event) { //_CODE_:SaveRecipe:637058:
  if (SaveRecipe.isEnabled() == true) {
    SaveRecipeToText();
  }
} //_CODE_:SaveRecipe:637058:

public void GetIngredients(GTextArea source, GEvent event) { //_CODE_:IngredientGetter:968721:
  listOfRecipeIngredients = IngredientGetter.getText();
} //_CODE_:IngredientGetter:968721:

public void nameCreator(GTextField source, GEvent event) { //_CODE_:CreatersName:850500:
  nameOfRecipeCreator = CreatersName.getText();
} //_CODE_:CreatersName:850500:

public void name(GTextField source, GEvent event) { //_CODE_:RecipeName:948173:
  nameOfNewRecipe = RecipeName.getText();
} //_CODE_:RecipeName:948173:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  RecipeSaver = new GPanel(this, 40, 30, 409, 310, "Save Your Recipes");
  RecipeSaver.setDraggable(false);
  RecipeSaver.setText("Save Your Recipes");
  RecipeSaver.setOpaque(true);
  RecipeSaver.addEventHandler(this, "RecipeSaving");
  Ingredients = new GLabel(this, 270, 30, 120, 20);
  Ingredients.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Ingredients.setText("Ingredients");
  Ingredients.setOpaque(false);
  SaveRecipe = new GButton(this, 10, 270, 80, 30);
  SaveRecipe.setText("Save Your Recipe");
  SaveRecipe.addEventHandler(this, "RecipeSaved");
  IngredientGetter = new GTextArea(this, 270, 60, 120, 240, G4P.SCROLLBARS_NONE);
  IngredientGetter.setOpaque(true);
  IngredientGetter.addEventHandler(this, "GetIngredients");
  CreatersName = new GTextField(this, 140, 60, 120, 20, G4P.SCROLLBARS_NONE);
  CreatersName.setOpaque(true);
  CreatersName.addEventHandler(this, "nameCreator");
  RecipeName = new GTextField(this, 10, 60, 120, 20, G4P.SCROLLBARS_NONE);
  RecipeName.setOpaque(true);
  RecipeName.addEventHandler(this, "name");
  Recipe = new GLabel(this, 10, 30, 120, 20);
  Recipe.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Recipe.setText("Recipe's Name");
  Recipe.setOpaque(false);
  Creator = new GLabel(this, 140, 30, 120, 20);
  Creator.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Creator.setText("Creator's Name");
  Creator.setOpaque(false);
  SavedLabel = new GLabel(this, 150, 130, 120, 30);
  SavedLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  SavedLabel.setText("Your Recipe Had Been Saved");
  SavedLabel.setOpaque(false);
  RecipeSaver.addControl(Ingredients);
  RecipeSaver.addControl(SaveRecipe);
  RecipeSaver.addControl(IngredientGetter);
  RecipeSaver.addControl(CreatersName);
  RecipeSaver.addControl(RecipeName);
  RecipeSaver.addControl(Recipe);
  RecipeSaver.addControl(Creator);
  RecipeSaver.addControl(SavedLabel);
}

// Variable declarations 
// autogenerated do not edit
GPanel RecipeSaver; 
GLabel Ingredients; 
GButton SaveRecipe; 
GTextArea IngredientGetter; 
GTextField CreatersName; 
GTextField RecipeName; 
GLabel Recipe; 
GLabel Creator; 
GLabel SavedLabel; 
