/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void name(GTextField source, GEvent event) { //_CODE_:RecipeName:489703:
  nameOfNewRecipe = RecipeName.getText();
} //_CODE_:RecipeName:489703:

public void nameCreator(GTextField source, GEvent event) { //_CODE_:CreatersName:416585:
  nameOfRecipeCreator = CreatersName.getText();
} //_CODE_:CreatersName:416585:

public void GetIngredients(GTextArea source, GEvent event) { //_CODE_:IngredientGetter:220050:
  listOfRecipeIngredients = IngredientGetter.getText();
} //_CODE_:IngredientGetter:220050:

public void RecipeSaved(GButton source, GEvent event) { //_CODE_:SaveRecipe:276698:
  if (SaveRecipe.isEnabled() == true) {
    SaveRecipeToText();
  }
} //_CODE_:SaveRecipe:276698:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  NameOfRecipe = new GLabel(this, 10, 17, 120, 20);
  NameOfRecipe.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  NameOfRecipe.setText("Recipe Name");
  NameOfRecipe.setOpaque(false);
  RecipeName = new GTextField(this, 10, 48, 120, 17, G4P.SCROLLBARS_NONE);
  RecipeName.setOpaque(true);
  RecipeName.addEventHandler(this, "name");
  NameOfCreator = new GLabel(this, 145, 17, 119, 20);
  NameOfCreator.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  NameOfCreator.setText("CreatorName");
  NameOfCreator.setOpaque(false);
  CreatersName = new GTextField(this, 145, 48, 120, 17, G4P.SCROLLBARS_NONE);
  CreatersName.setOpaque(true);
  CreatersName.addEventHandler(this, "nameCreator");
  Ingredients = new GLabel(this, 282, 16, 121, 20);
  Ingredients.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Ingredients.setText("List Of Ingredients");
  Ingredients.setOpaque(false);
  IngredientGetter = new GTextArea(this, 283, 48, 120, 80, G4P.SCROLLBARS_NONE);
  IngredientGetter.setOpaque(true);
  IngredientGetter.addEventHandler(this, "GetIngredients");
  SaveRecipe = new GButton(this, 163, 200, 80, 30);
  SaveRecipe.setText("Save Your Recipe");
  SaveRecipe.addEventHandler(this, "RecipeSaved");
}

// Variable declarations 
// autogenerated do not edit
GLabel NameOfRecipe; 
GTextField RecipeName; 
GLabel NameOfCreator; 
GTextField CreatersName; 
GLabel Ingredients; 
GTextArea IngredientGetter; 
GButton SaveRecipe; 
